[workspace]
resolver = "2" # What does this do?

[package]
name = "vger-rs"
version = "0.1.0"
authors = ["Taylor Holliday <taylor@audulus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"
wgpu = "0.12.0"
