[workspace]
resolver = "2" # What does this do?

[package]
name = "vger-rs"
version = "0.1.0"
authors = ["Taylor Holliday <taylor@audulus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[patch.crates-io]
naga = { git = "https://github.com/audulus/naga", branch = "MSL-address-space-backport-v0.8" }

[dependencies]
winit = "0.26.0"
wgpu = "0.12.0"
futures = "0.3"
euclid = "0.22.6"
mem_align = { git="https://github.com/adamnemecek/mem_align" }
png = "0.16"
fontdue = "0.6.3"
rectangle-pack = "0.4.2"
rect_packer = "0.2.1"
rand = "0.7.3"