name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    # Note that we can't run the tests because GitHub CI doesn't have GPUs.
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
